### ISSUE TITLE
What exactly is the output?

### ISSUE THREAD

**Issue by IntrinsicInnovation** [ryancdotorg/brainflayer#191]
thanks for this program by the way!  I've ran this a few times, and when I use a wordlist like so: $brainflayer -v -b btc.blf -i wordlist.txt, I get a 40 character long address (I think), then a word.  but, how is this cracking anything?  Wouldn't I need the private key? is the 40 character output a private key or an address or?  Plus, aren't the wallet word lists 12 words long?  

Plus, I did try just the incremental method : $brainflayer  -c e -v -b eth.blf -I 0000000000000000000000000000000000000000000000000000000000000001
, and I get different results that seem to show an Ethereum address, then supposedly
a private key  so    Addressxxxxxxxxxxxxxxxxx : PrivateKeyxxxxxxxxxxxxxxxxxxxxxxxx    
, but all of them are false positives, so zero balance, and the address was never
used it looks like?  so, I'm not 100% sure what I'm looking at, 
or what other steps I need to take to run it properly?  I'm using ubuntu 22.04 or thereabouts.  
I get no errors compiling and running,

Thanks!

**Comment by IntrinsicInnovation** [comment]
you should know this.  easy question.  I'm questioning whether this  produces useful information or not?

**Comment by ryancdotorg** [comment]
I don't appreciate your tone.

try ctrl-f "false positive" on the readme

**Comment by IntrinsicInnovation** [comment]
lol, why am I getting ethereum addresses?  is it supposed to do that, or what is wrong with my parameters?

**Comment by ryancdotorg** [comment]
false positives are addressed in the readme

brainflayer outputs 160 bit values used as internal representation of addresses by many cryptocurrencies, along with the matching input. as a deliberate design decision, it does not output private keys unless private keys were the input

**Comment by IntrinsicInnovation** [comment]
ok, thanks, sorry for that.  Also, when I type it in in blockchain.com it just says ether addresses.  still not 100% clear on that, as in blockchain.com it says its ether.  I do get a private key too, but doesn't seem to relate to address?  tried as a bitcoin address and it's always 0 balance.
